// Generated by CoffeeScript 1.7.1
(function() {
  var Box;

  Box = (function() {
    function Box(x, y, w, h, color) {
      var _ref;
      _ref = M(x, y, w, h).diverge([0, 0, 0, 0]), this.x = _ref[0], this.y = _ref[1], this.w = _ref[2], this.h = _ref[3];
      this.color = M(color).otherwise({
        value: "#000"
      });
    }

    Box.prototype.intersects = function(obj) {
      var a, b, c, d, m, n, o, p, w, x, y, z;
      a = this.contains(obj.x, obj.y);
      b = this.contains(obj.x + obj.w, obj.y);
      c = this.contains(obj.x, obj.y + obj.h);
      d = this.contains(obj.x + obj.w, obj.y + obj.h);
      m = obj.contains(this.x, this.y);
      n = obj.contains(this.x + this.w, this.y);
      o = obj.contains(this.x, this.y + this.h);
      p = obj.contains(this.x + this.w, this.y + this.h);
      w = M(a, c);
      x = M(b, d);
      y = M(m, o);
      z = M(n, p);
      this.hit = w.elser(x.elser(y.elser(z.elser(false))));
      return this.hit;
    };

    Box.prototype.move = function(dx, dy) {
      this.x = this.x + dx;
      this.y = this.y + dy;
      return this;
    };

    Box.prototype.contains = function(x, y) {
      if (x >= this.x && x <= this.x + this.w && y >= this.y && y <= this.y + this.h) {
        return true;
      } else {
        return false;
      }
    };

    Box.prototype.update = function(unit, canvas) {};

    Box.prototype.render = function(ctx) {
      ctx.fillStyle = this.color.value;
      return ctx.fillRect(this.x, this.y, this.w, this.h);
    };

    return Box;

  })();

  window.Box = Box;

}).call(this);
