// Generated by CoffeeScript 1.7.1
(function() {
  var EventPage;

  EventPage = (function() {
    function EventPage(code, ev) {
      this.root = code.root;
      this.canvas = code.canvas;
      this.ctx = code.ctx;
      this.once = false;
      this.reset = false;
      this.events = {
        "end": "Game Over",
        "win": "You Win!"
      };
    }

    EventPage.prototype.set = function(ev) {
      this.event = ev;
      this.text = this.events[ev];
      return console.log(this.text);
    };

    EventPage.prototype.update = function() {
      var epDiv, epText;
      if (!this.once) {
        epDiv = document.createElement("div");
        epDiv.id = "evpg";
        epText = document.createTextNode(this.text);
        this.root.appendChild(epDiv).appendChild(epText);
        this.once = true;
        return document.addEventListener("click", function(e) {
          if (this.event === "end") {
            return window.location.reload(true);
          }
        });
      }
    };

    EventPage.prototype.render = function() {
      this.ctx.fillStyle = "#000";
      return this.ctx.fillRect(0, 0, this.canvas.width, this.canvas.height);
    };

    return EventPage;

  })();

  window.EventPage = EventPage;

}).call(this);
