// Generated by CoffeeScript 1.7.1
(function() {
  var Light;

  Light = (function() {
    function Light(player, unit) {
      var _ref;
      this.you = player;
      this.unit = unit;
      _ref = [0, 0, 100, 0.2], this.h = _ref[0], this.s = _ref[1], this.l = _ref[2], this.a = _ref[3];
      this.color = new Color(this.h, this.s, this.l, this.a);
      this.radius = this.you.w * 1.5;
      this.center = [this.you.x + (this.you.w / 2), this.you.y + (this.you.h / 2) - (this.unit / 4)];
    }

    Light.prototype.brightness = function(delta) {
      return this.color = new Color(this.h, this.s, this.l, this.a + delta);
    };

    Light.prototype.ligthen = function() {
      return this.brightness(0.1);
    };

    Light.prototype.darken = function() {
      return this.brightness(-0.1);
    };

    Light.prototype.grow = function() {
      return this.radius + 1;
    };

    Light.prototype.shrink = function() {
      return this.radius - 1;
    };

    Light.prototype.update = function(player) {
      this.you = player;
      return this.center = [this.you.x + (this.you.w / 2), this.you.y + (this.you.h / 2) - (this.unit / 4)];
    };

    Light.prototype.render = function(ctx) {
      ctx.fillStyle = this.color.value;
      ctx.beginPath();
      ctx.arc(this.center[0], this.center[1], this.radius, 0, 2 * pi);
      ctx.fill();
      return ctx.closePath();
    };

    return Light;

  })();

  window.Light = Light;

}).call(this);
