// Generated by CoffeeScript 1.7.1
(function() {
  var Mob,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Mob = (function(_super) {
    __extends(Mob, _super);

    function Mob(x, y) {
      Mob.__super__.constructor.call(this, x, y, 50, 50, new Color(0, 0, 0));
      this.ground = false;
      this.falling = true;
    }

    Mob.prototype.update = function(player, unit, canvas) {
      if (this.x < 0) {
        this.x = 0;
      }
      if (this.y < 0) {
        this.y = 0;
      }
      if (this.x + this.w > canvas.width) {
        this.x = canvas.width - this.w;
      }
      if (this.y + this.h > canvas.height) {
        return this.y = canvas.height - this.h;
      }
    };

    return Mob;

  })(Box);

  window.Mob = Mob;

}).call(this);
