// Generated by CoffeeScript 1.7.1
(function() {
  var Player,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Player = (function(_super) {
    __extends(Player, _super);

    function Player(x, y, unit) {
      var scale;
      scale = unit * (3 / 4);
      Player.__super__.constructor.call(this, x, y, scale, scale, new Color(210, 50, 50));
      this.ground = false;
      this.jumping = false;
      this.falling = true;
      this.dead = false;
      this.hp = 3;
      this.light = new Light(this);
    }

    Player.prototype.damage = function(dmg) {
      return this.hp = this.hp - dmg;
    };

    Player.prototype.update = function(key, unit, canvas) {
      if (this.dead) {
        return;
      }
      if (this.hp < 1) {
        this.dead = true;
        console.log("Dead");
      }
      if ((((key[87] || key[32]) && this.ground) || this.jumping) && !this.falling) {
        if (key[65]) {
          this.move(-(unit / 20), 0);
        }
        if (key[68]) {
          this.move(unit / 20, 0);
        }
        if (this.jumping === false || this.jy === void 0) {
          this.jy = this.y - (unit * 2);
        }
        this.ground = false;
        this.jumping = true;
        this.move(0, -(unit / 16));
        if (this.y <= this.jy) {
          this.jumping = false;
          this.falling = true;
        }
      } else {
        if (key[65]) {
          this.x = this.x - (unit / 20);
          this.falling = true;
        }
        if (key[68]) {
          this.x = this.x + (unit / 20);
          this.falling = true;
        }
      }
      if (this.x <= 0) {
        this.x = 0;
      }
      if (this.y <= 0) {
        this.y = 0;
        this.falling = true;
        this.jumping = false;
      }
      if (this.x + this.w > canvas.width) {
        return this.x = canvas.width - this.w;
      }
    };

    return Player;

  })(Box);

  window.Player = Player;

}).call(this);
