// Generated by CoffeeScript 1.7.1
(function() {
  var Color;

  Color = (function() {
    function Color(h, s, l, a) {
      var _ref;
      _ref = M(h, s, l).diverge([0, 0, 0]), this.h = _ref[0], this.s = _ref[1], this.l = _ref[2];
      this.a = M(a).otherwise(1);
      this.value = "hsla(" + this.h + ", " + this.s + "%, " + this.l + "%, " + this.a + ")";
    }

    return Color;

  })();

  window.Color = Color;

}).call(this);
